### ISSUE TITLE
Use GitHub Actions to Deploy automatically to GitHub Packages

### ISSUE THREAD

**Issue by jgriss** [bigbio/pgatk-io#3]
@ypriverol 

GitHub now also provides a maven repository which is accessible through GitHub actions.

I suggest to move this package to the GitHub mvn repo to automatically update the latest snapshot version as soon as we have a successful merge into master.

Otherwise, we have to update the mvn package manually which is causing some issues on my side.

**Comment by ypriverol** [comment]
I just requested a project in maven central easy for deployments from Github Actions. If the repo can't be granted we can configure it using EBI repos.

**Comment by ypriverol** [comment]
Hi @jgriss apparently you need to own the domain bigbio.org to have the groupId org.bigbio, maven central recommended using `io.github.bigbio` as groupId is that ok for you?

**Comment by jgriss** [comment]
@ypriverol Absolutely! I have no preference what kind of groupId we use. Whatever you prefer!

**Comment by jgriss** [comment]
@ypriverol Question: The `release action` now has the same configuration as the snapshot action. Do you know if there's a way to only trigger the `release action` when we really want a release?

**Comment by ypriverol** [comment]
If you see we have an small difference in the server I’d between both configurations. The cool things will be to trigger one or the other depending of if is a prerelease or release. I will investigate on that

**Comment by ypriverol** [comment]
Done.
